# Generated by Django 4.2.13 on 2025-12-11 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('paid', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('customer_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('business_leader', 'Business Leader'), ('regional_manager', 'Regional Manager'), ('manager', 'Manager'), ('vendor', 'Vendor'), ('user', 'User')], default='user', max_length=36)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, max_length=12, null=True)),
                ('i_address', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('i_country', models.CharField(max_length=64)),
                ('i_zip', models.IntegerField(default='0')),
                ('a_address', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('a_country', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('a_zip', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('vat', models.CharField(default='', max_length=16, verbose_name='Vat')),
                ('business', models.CharField(default='', max_length=120, verbose_name='Business')),
                ('business_address', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('website_url', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Website')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('allow_access', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=800)),
                ('link', models.CharField(max_length=800)),
                ('image_link', models.CharField(max_length=800)),
                ('price', models.DecimalField(decimal_places=2, max_digits=60)),
                ('relative_price', models.DecimalField(decimal_places=2, max_digits=65)),
                ('vendor', models.CharField(default='None', max_length=100)),
                ('brand', models.CharField(default='None', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=300)),
                ('scraped', models.CharField(max_length=300)),
                ('last_scraped', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('website', models.URLField(max_length=120)),
                ('address', models.JSONField(blank=True, default=dict, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='XMLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='xml_uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='backend.products')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDataResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_token', models.CharField(blank=True, max_length=400, null=True, verbose_name='Password reset token')),
                ('valid_to', models.DateTimeField(verbose_name='Valid Till')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_resetpassword', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=300)),
                ('results', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='scraper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.scraper'),
        ),
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='backend.vendor'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_selected', models.CharField(max_length=500)),
                ('transaction_amount', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=400)),
                ('image_link', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=60)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=65)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('relative_price', models.DecimalField(decimal_places=2, max_digits=65)),
                ('vendor', models.CharField(default='None', max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='backend.vendor')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='backend.tag'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='users_data', to='backend.vendor'),
        ),
    ]
