# Generated by Django 4.2.13 on 2026-01-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShyfterEmployee',
            fields=[
                ('id', models.CharField(help_text='Shyfter employee ID', max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='User type (admin, employee, etc.)', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Whether the employee member is active')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('civil_state', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('national_number', models.CharField(blank=True, max_length=50, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(default='en', help_text='User language', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=100, null=True)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(default='Dendermonde', help_text='employee location', max_length=100)),
                ('address', models.JSONField(blank=True, default=dict, help_text='Address object')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Settings object')),
                ('defaults', models.JSONField(blank=True, default=dict, help_text='Defaults/worktime object')),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='Custom fields array')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full raw employee payload from Shyfter')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our DB')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated in our DB')),
            ],
            options={
                'db_table': 'shyfter_employee',
                'ordering': ['display_name', 'id'],
                'indexes': [models.Index(fields=['active'], name='shyfter_emp_active_d1a5cf_idx'), models.Index(fields=['type'], name='shyfter_emp_type_d04956_idx'), models.Index(fields=['email'], name='shyfter_emp_email_4965f8_idx'), models.Index(fields=['location'], name='shyfter_emp_locatio_4ed38f_idx')],
            },
        ),
    ]
