# Generated by Django 4.0 on 2023-09-09 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='a_address',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='a_country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='a_zip',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='i_address',
            field=models.CharField(default='Haha', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='i_country',
            field=models.CharField(default='Usa', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='i_zip',
            field=models.IntegerField(default=54000),
            preserve_default=False,
        ),
    ]
