# Generated by Django 4.2.13 on 2026-01-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_shyfteremployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shyfteremployee',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shyfteremployee',
            name='id',
            field=models.CharField(help_text='Shyfter employee ID', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shyfteremployee',
            name='national_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shyfteremployee',
            name='type',
            field=models.CharField(help_text='User type (admin, employee, etc.)', max_length=50),
        ),
    ]
