# Generated by Django 4.2.13 on 2026-01-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_shyfteremployee_iban_alter_shyfteremployee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shyfteremployee',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shyfteremployee',
            name='type',
            field=models.CharField(help_text='User type (admin, employee, etc.)', max_length=100),
        ),
    ]
