# Generated by Django 4.0 on 2023-09-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_userdata_a_address_userdata_a_country_userdata_a_zip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=200)),
                ('image_link', models.CharField(max_length=200)),
                ('price', models.BooleanField()),
                ('vendor', models.CharField(default='None', max_length=100)),
                ('brand', models.CharField(default='None', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=200)),
                ('image_link', models.CharField(max_length=200)),
                ('price', models.BooleanField()),
                ('vendor', models.CharField(default='None', max_length=100)),
                ('brand', models.CharField(default='None', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=300)),
                ('results', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=200)),
                ('image_link', models.CharField(max_length=200)),
                ('price', models.BooleanField()),
                ('quantity', models.BooleanField()),
                ('unit', models.CharField(max_length=100)),
                ('vendor', models.CharField(default='None', max_length=100)),
                ('brand', models.CharField(default='None', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.userdata')),
            ],
        ),
    ]
