# Generated by Django 4.2.13 on 2026-01-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_shyfteremployee_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShyfterEmployeeClocking',
            fields=[
                ('id', models.CharField(help_text='Shyfter clocking ID', max_length=255, primary_key=True, serialize=False)),
                ('shift_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('work_date', models.DateField(help_text='Derived date from start time')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Total worked minutes')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('clock_in', models.JSONField(blank=True, default=dict)),
                ('clock_out', models.JSONField(blank=True, default=dict)),
                ('breaks', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockings', to='backend.shyfteremployee')),
            ],
            options={
                'db_table': 'shyfter_employee_clocking',
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['employee', 'work_date'], name='shyfter_emp_employe_4508bb_idx'), models.Index(fields=['location'], name='shyfter_emp_locatio_3e9513_idx')],
            },
        ),
    ]
