# Generated by Django 4.0 on 2023-09-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_orders_price_alter_orders_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='link',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='vendor',
        ),
        migrations.AddField(
            model_name='orders',
            name='relative_price',
            field=models.DecimalField(decimal_places=2, default=1.22, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.products'),
            preserve_default=False,
        ),
    ]
