# Generated by Django 4.2.13 on 2026-01-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_shyfteremployeeclocking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShyfterEmployeeShift',
            fields=[
                ('id', models.CharField(help_text='Shyfter shift ID', max_length=255, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('work_date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('breaks', models.JSONField(blank=True, default=dict)),
                ('social_secretary', models.JSONField(blank=True, default=dict)),
                ('location', models.CharField(max_length=100)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='backend.shyfteremployee')),
            ],
            options={
                'db_table': 'shyfter_employee_shift',
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['employee', 'work_date'], name='shyfter_emp_employe_c638ed_idx'), models.Index(fields=['location'], name='shyfter_emp_locatio_f18605_idx')],
            },
        ),
    ]
