# Generated by Django 4.0 on 2023-09-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_wishlist_brand_remove_wishlist_image_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=300)),
                ('scraped', models.CharField(max_length=300)),
                ('last_scraped', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
