# Generated by Django 4.0 on 2023-09-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_scraper'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='scraper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.scraper'),
        ),
    ]
