# Generated by Django 4.0 on 2023-09-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_products_scraper'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='relative_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=100),
            preserve_default=False,
        ),
    ]
