# Generated by Django 4.0 on 2023-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_products_relative_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='business',
            field=models.CharField(default='None', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='vat',
            field=models.CharField(default='None', max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=60),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=65),
        ),
        migrations.AlterField(
            model_name='orders',
            name='relative_price',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=60),
        ),
        migrations.AlterField(
            model_name='products',
            name='relative_price',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
    ]
