# Generated by Django 4.0 on 2023-12-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_userdata_business_userdata_vat_alter_orders_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_link',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='products',
            name='link',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='i_address',
            field=models.CharField(default='None', max_length=800),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='i_country',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='i_zip',
            field=models.IntegerField(default='0'),
        ),
    ]
