# Generated by Django 4.0 on 2024-02-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_products_image_link_alter_products_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='package_selected',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_amount',
        ),
        migrations.AddField(
            model_name='userdata',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
