# Generated by Django 4.0 on 2024-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_package_selected_payment_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='customer_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
