# Generated by Django 4.0 on 2024-02-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_userdata_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
