# Generated by Django 4.0 on 2024-02-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_userdata_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
