# Generated by Django 4.2.13 on 2024-06-04 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('website', models.URLField(max_length=120)),
                ('address', models.JSONField(blank=True, default=dict, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='business_address',
            field=models.CharField(blank=True, default='', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='website_url',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='a_address',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='a_country',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='a_zip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='business',
            field=models.CharField(default='', max_length=120, verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='i_address',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='i_country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='role',
            field=models.CharField(default='user', max_length=36, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='vat',
            field=models.CharField(default='', max_length=16, verbose_name='Vat'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_selected', models.CharField(max_length=500)),
                ('transaction_amount', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='backend.vendor'),
        ),
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='backend.vendor'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='backend.tag'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='users_data', to='backend.vendor'),
        ),
    ]
