# Generated by Django 4.2.13 on 2024-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_tag_vendor_userdata_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
