# Generated by Django 4.2.13 on 2024-06-14 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_orders_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_token', models.CharField(blank=True, max_length=400, null=True, verbose_name='Password reset token')),
                ('valid_to', models.DateTimeField(verbose_name='Valid Till')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_resetpassword', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
