# Generated by Django 4.2.13 on 2024-06-14 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_payment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataresetpassword',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_resetpassword', to=settings.AUTH_USER_MODEL),
        ),
    ]
