# Generated by Django 4.2.13 on 2024-06-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_userdataresetpassword_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdataresetpassword',
            old_name='user_id',
            new_name='customer',
        ),
    ]
