# Generated by Django 4.2.13 on 2024-06-20 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_rename_user_id_userdataresetpassword_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataresetpassword',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_resetpassword', to=settings.AUTH_USER_MODEL),
        ),
    ]
