# Generated by Django 4.2.13 on 2024-06-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_userdataresetpassword_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='image_link',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='orders',
            name='link',
            field=models.CharField(max_length=400),
        ),
    ]
