# Generated by Django 4.2.13 on 2024-06-26 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_orders_brand_alter_orders_image_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
