# Generated by Django 5.2.7 on 2025-10-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_searches_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='xml_uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
