# Generated by Django 4.2.13 on 2025-11-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_xmlfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('vendor', 'Vendor'), ('user', 'User')], default='user', max_length=36),
        ),
    ]
