# Generated by Django 4.2.13 on 2025-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigIntegerField(help_text='Shopify order ID', primary_key=True, serialize=False)),
                ('app_id', models.BigIntegerField(blank=True, help_text='App ID', null=True)),
                ('buyer_accepts_marketing', models.BooleanField(default=False, help_text='Buyer accepts marketing')),
                ('cancel_reason', models.CharField(blank=True, help_text='Cancel reason', max_length=255, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Cancelled at', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Closed at', null=True)),
                ('confirmation_number', models.CharField(blank=True, help_text='Confirmation number', max_length=100, null=True)),
                ('confirmed', models.BooleanField(default=False, help_text='Order confirmed')),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True)),
                ('currency', models.CharField(blank=True, help_text='Currency code', max_length=10, null=True)),
                ('customer_locale', models.CharField(blank=True, help_text='Customer locale', max_length=20, null=True)),
                ('device_id', models.BigIntegerField(blank=True, help_text='Device ID', null=True)),
                ('duties_included', models.BooleanField(default=False, help_text='Duties included')),
                ('email', models.EmailField(blank=True, help_text='Customer email', max_length=254, null=True)),
                ('estimated_taxes', models.BooleanField(default=False, help_text='Estimated taxes')),
                ('financial_status', models.CharField(blank=True, help_text='Financial status', max_length=50, null=True)),
                ('fulfillment_status', models.CharField(blank=True, help_text='Fulfillment status', max_length=50, null=True)),
                ('location_id', models.BigIntegerField(blank=True, help_text='Location ID', null=True)),
                ('merchant_business_entity_id', models.CharField(blank=True, help_text='Merchant business entity ID', max_length=255, null=True)),
                ('merchant_of_record_app_id', models.BigIntegerField(blank=True, help_text='Merchant of record app ID', null=True)),
                ('name', models.CharField(blank=True, help_text='Order name', max_length=255, null=True)),
                ('note', models.TextField(blank=True, help_text='Order note', null=True)),
                ('number', models.IntegerField(blank=True, help_text='Order number', null=True)),
                ('order_number', models.IntegerField(blank=True, help_text='Order number (display)', null=True)),
                ('presentment_currency', models.CharField(blank=True, help_text='Presentment currency', max_length=10, null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Processed at', null=True)),
                ('subtotal_price', models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal price', max_digits=10, null=True)),
                ('tags', models.CharField(blank=True, help_text='Order tags', max_length=500, null=True)),
                ('tax_exempt', models.BooleanField(default=False, help_text='Tax exempt')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Total weight', max_digits=10, null=True)),
                ('user_id', models.BigIntegerField(blank=True, help_text='User ID', null=True)),
                ('current_subtotal_price', models.DecimalField(blank=True, decimal_places=2, help_text='Current subtotal price', max_digits=10, null=True)),
                ('current_total_discounts', models.DecimalField(blank=True, decimal_places=2, help_text='Current total discounts', max_digits=10, null=True)),
                ('current_total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Current total price', max_digits=10, null=True)),
                ('current_total_tax', models.DecimalField(blank=True, decimal_places=2, help_text='Current total tax', max_digits=10, null=True)),
                ('total_discounts', models.DecimalField(blank=True, decimal_places=2, help_text='Total discounts', max_digits=10, null=True)),
                ('total_line_items_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total line items price', max_digits=10, null=True)),
                ('total_outstanding', models.DecimalField(blank=True, decimal_places=2, help_text='Total outstanding', max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total price', max_digits=10, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, help_text='Total tax', max_digits=10, null=True)),
                ('total_tip_received', models.DecimalField(blank=True, decimal_places=2, help_text='Total tip received', max_digits=10, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, help_text='Customer ID', null=True)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email', max_length=254, null=True)),
                ('customer_first_name', models.CharField(blank=True, help_text='Customer first name', max_length=255, null=True)),
                ('customer_last_name', models.CharField(blank=True, help_text='Customer last name', max_length=255, null=True)),
                ('billing_address', models.JSONField(blank=True, default=dict, help_text='Billing address')),
                ('customer_data', models.JSONField(blank=True, default=dict, help_text='Full customer data')),
                ('line_items', models.JSONField(blank=True, default=list, help_text='Line items array')),
                ('shipping_address', models.JSONField(blank=True, default=dict, help_text='Shipping address')),
                ('shipping_lines', models.JSONField(blank=True, default=list, help_text='Shipping lines array')),
                ('discount_codes', models.JSONField(default=list, blank=True, help_text='Discount codes array')),
                ('note_attributes', models.JSONField(default=list, blank=True, help_text='Note attributes array')),
                ('payment_gateway_names', models.JSONField(default=list, blank=True, help_text='Payment gateway names array')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full raw order payload from Shopify')),
                ('created_at', models.DateTimeField(blank=True, help_text='Order created at (from Shopify)', null=True)),
                ('updated_at', models.DateTimeField(blank=True, help_text='Order updated at (from Shopify)', null=True)),
                ('local_created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our DB')),
                ('local_updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated in our DB')),
            ],
            options={
                'db_table': 'shopify_orders',
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['financial_status'], name='shopify_or_financi_idx'),
                    models.Index(fields=['fulfillment_status'], name='shopify_or_fulfill_idx'),
                    models.Index(fields=['customer_id'], name='shopify_or_custome_idx'),
                    models.Index(fields=['created_at'], name='shopify_or_created_idx'),
                    models.Index(fields=['email'], name='shopify_or_email_idx'),
                    models.Index(fields=['order_number'], name='shopify_or_order_n_idx'),
                    models.Index(fields=['name'], name='shopify_or_name_idx'),
                ],
            },
        ),
    ]
