# Generated by Django 4.2.13 on 2025-12-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shopifyorder',
            new_name='shopify_ord_financi_97f562_idx',
            old_name='shopify_or_financi_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyorder',
            new_name='shopify_ord_fulfill_a17fd6_idx',
            old_name='shopify_or_fulfill_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyorder',
            new_name='shopify_ord_custome_7ecd78_idx',
            old_name='shopify_or_custome_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyorder',
            new_name='shopify_ord_created_68fb2f_idx',
            old_name='shopify_or_created_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyorder',
            new_name='shopify_ord_email_fbb1a7_idx',
            old_name='shopify_or_email_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyorder',
            new_name='shopify_ord_order_n_2c1a06_idx',
            old_name='shopify_or_order_n_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyorder',
            new_name='shopify_ord_name_5c3b69_idx',
            old_name='shopify_or_name_idx',
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='location',
            field=models.CharField(default='Dendermonde', help_text='Order location', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='billing_address',
            field=models.JSONField(blank=True, default=dict, help_text='Billing address', null=True),
        ),
        migrations.AddIndex(
            model_name='shopifyorder',
            index=models.Index(fields=['location'], name='shopify_ord_locatio_eb7963_idx'),
        ),
    ]
