# Generated by Django 4.2.13 on 2025-12-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightspeedOrder',
            fields=[
                ('id', models.BigIntegerField(help_text='Lightspeed order ID', primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField(blank=True, help_text='Order delivery date', null=True)),
                ('creation_date', models.DateTimeField(blank=True, help_text='Order creation date', null=True)),
                ('type', models.CharField(blank=True, help_text='Order type (e.g., delivery)', max_length=50, null=True)),
                ('receipt_id', models.BigIntegerField(blank=True, help_text='Receipt ID', null=True)),
                ('link_to_open_receipt_on_table', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, help_text='Order status (e.g., PROCESSED)', max_length=50, null=True)),
                ('table_id', models.BigIntegerField(blank=True, help_text='Table ID', null=True)),
                ('customer_id', models.BigIntegerField(blank=True, help_text='Customer ID', null=True)),
                ('external_reference', models.CharField(blank=True, help_text='External reference', max_length=255, null=True)),
                ('order_items', models.JSONField(blank=True, default=list, help_text='Order items array')),
                ('order_payments', models.JSONField(blank=True, default=list, help_text='Order payments array')),
                ('order_tax_info', models.JSONField(blank=True, default=list, help_text='Order tax info array')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full raw order payload from Lightspeed')),
                ('note', models.TextField(blank=True, help_text='Order notes', null=True)),
                ('number_of_customers', models.IntegerField(default=0, help_text='Number of customers')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our DB')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated in our DB')),
            ],
            options={
                'db_table': 'lightspeed_orders',
                'ordering': ['-creation_date', '-id'],
                'indexes': [models.Index(fields=['status'], name='lightspeed__status_3a8d8b_idx'), models.Index(fields=['customer_id'], name='lightspeed__custome_172341_idx'), models.Index(fields=['creation_date'], name='lightspeed__creatio_c64a6f_idx'), models.Index(fields=['type'], name='lightspeed__type_fd7003_idx')],
            },
        ),
    ]
