# Generated by Django 4.2.13 on 2025-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeed_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightspeedProduct',
            fields=[
                ('id', models.BigIntegerField(help_text='Lightspeed product ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Product name', max_length=255, null=True)),
                ('visible', models.BooleanField(default=True, help_text='Whether product is visible')),
                ('image_location', models.CharField(blank=True, help_text='Image location URL', max_length=500, null=True)),
                ('kitchen_image_location', models.CharField(blank=True, help_text='Kitchen image location URL', max_length=500, null=True)),
                ('cfd_image_location', models.CharField(blank=True, help_text='CFD image location URL', max_length=500, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Product price', max_digits=10, null=True)),
                ('price_without_vat', models.DecimalField(blank=True, decimal_places=2, help_text='Price without VAT', max_digits=10, null=True)),
                ('takeaway_price', models.DecimalField(blank=True, decimal_places=2, help_text='Takeaway price', max_digits=10, null=True)),
                ('takeaway_price_without_vat', models.DecimalField(blank=True, decimal_places=2, help_text='Takeaway price without VAT', max_digits=10, null=True)),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, help_text='Delivery price', max_digits=10, null=True)),
                ('delivery_price_without_vat', models.DecimalField(blank=True, decimal_places=2, help_text='Delivery price without VAT', max_digits=10, null=True)),
                ('product_type', models.CharField(blank=True, help_text='Product type', max_length=100, null=True)),
                ('sku', models.CharField(blank=True, help_text='SKU code', max_length=100, null=True)),
                ('tax_class', models.CharField(blank=True, help_text='Tax class', max_length=100, null=True)),
                ('delivery_tax_class', models.CharField(blank=True, help_text='Delivery tax class', max_length=100, null=True)),
                ('takeaway_tax_class', models.CharField(blank=True, help_text='Takeaway tax class', max_length=100, null=True)),
                ('stock_amount', models.IntegerField(default=0, help_text='Stock amount')),
                ('stock_management_enabled', models.BooleanField(default=False, help_text='Whether stock management is enabled')),
                ('group_ids', models.JSONField(blank=True, default=list, help_text='Product group IDs array')),
                ('additions', models.JSONField(blank=True, default=list, help_text='Product additions array')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full raw product payload from Lightspeed')),
                ('info', models.TextField(blank=True, help_text='Product information/description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our DB')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated in our DB')),
            ],
            options={
                'db_table': 'lightspeed_products',
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['visible'], name='lightspeed__visible_8a2b4c_idx'),
                    models.Index(fields=['sku'], name='lightspeed__sku_9c3d5e_idx'),
                    models.Index(fields=['product_type'], name='lightspeed__produc_0f1a2b_idx'),
                    models.Index(fields=['stock_management_enabled'], name='lightspeed__stock__3c4d5e_idx'),
                ],
            },
        ),
    ]
