# Generated by Django 4.2.13 on 2025-12-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeed_integration', '0002_lightspeedproduct'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lightspeedproduct',
            new_name='lightspeed__visible_ff07bb_idx',
            old_name='lightspeed__visible_8a2b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='lightspeedproduct',
            new_name='lightspeed__sku_44b644_idx',
            old_name='lightspeed__sku_9c3d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='lightspeedproduct',
            new_name='lightspeed__product_fd51b5_idx',
            old_name='lightspeed__produc_0f1a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='lightspeedproduct',
            new_name='lightspeed__stock_m_7e9c31_idx',
            old_name='lightspeed__stock__3c4d5e_idx',
        ),
    ]
