# Generated by Django 4.2.13 on 2025-12-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeed_integration', '0003_rename_lightspeed__visible_8a2b4c_idx_lightspeed__visible_ff07bb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightspeedorder',
            name='location',
            field=models.CharField(default='Dendermonde', help_text='Order location', max_length=100),
        ),
        migrations.AddIndex(
            model_name='lightspeedorder',
            index=models.Index(fields=['location'], name='lightspeed__locatio_2d7c72_idx'),
        ),
    ]
