# Generated by Django 4.2.13 on 2025-12-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeed_integration', '0004_lightspeedorder_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightspeedProductGroup',
            fields=[
                ('id', models.BigIntegerField(help_text='Lightspeed product group ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Product group name', max_length=255, null=True)),
                ('sequence', models.IntegerField(default=0, help_text='Display sequence')),
                ('visible', models.BooleanField(default=True, help_text='Whether the group is visible')),
                ('category_id', models.BigIntegerField(blank=True, help_text='Category ID', null=True)),
                ('shortcut_category', models.BooleanField(default=False, help_text='Whether group is a shortcut category')),
                ('products', models.JSONField(blank=True, default=list, help_text='Products under this group')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full raw product group payload from Lightspeed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in our DB')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated in our DB')),
            ],
            options={
                'db_table': 'lightspeed_product_groups',
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['visible'], name='lightspeed__visible_d40a0b_idx'), models.Index(fields=['category_id'], name='lightspeed__categor_6dab6e_idx'), models.Index(fields=['sequence'], name='lightspeed__sequenc_3d653e_idx')],
            },
        ),
    ]
