# Generated by Django 4.2.13 on 2025-12-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeed_integration', '0005_lightspeedproductgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightspeedproductgroup',
            name='location',
            field=models.CharField(default='Dendermonde', help_text='Order location', max_length=100),
        ),
    ]
