# Generated by Django 4.2.13 on 2025-12-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeed_integration', '0006_lightspeedproductgroup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightspeedproduct',
            name='location',
            field=models.CharField(default='Dendermonde', help_text='Product location', max_length=100),
        ),
        migrations.AlterField(
            model_name='lightspeedproductgroup',
            name='location',
            field=models.CharField(default='Dendermonde', help_text='Product location', max_length=100),
        ),
    ]
