# Generated by Django 4.2.13 on 2026-01-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeed_integration', '0007_lightspeedproduct_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightspeedReceipt',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('table_id', models.BigIntegerField(blank=True, null=True)),
                ('floor_id', models.BigIntegerField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('customer_uuid', models.UUIDField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('print_date', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_without_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_customers', models.IntegerField(default=0)),
                ('current_course', models.IntegerField(blank=True, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('payments', models.JSONField(blank=True, default=list)),
                ('tax_info', models.JSONField(blank=True, default=list)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('location', models.CharField(default='Dendermonde', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lightspeed_financial_receipts',
                'ordering': ['-creation_date', '-id'],
                'indexes': [models.Index(fields=['creation_date'], name='lightspeed__creatio_ac6571_idx'), models.Index(fields=['status'], name='lightspeed__status_8c000c_idx'), models.Index(fields=['type'], name='lightspeed__type_dc538a_idx'), models.Index(fields=['location'], name='lightspeed__locatio_a01c8d_idx')],
            },
        ),
    ]
